### ISSUE TITLE
Can we integrate both model backend and AzureADtoken backend for django rest framework?

### ISSUE THREAD

**Issue by ranvijay-sachan** [jobec/django-auth-adfs#84]
In my project we are dealing with micro-services sending JWT token between micro services to authenticate API's.

If you have some sample code please share the link.

Some micro-services take more than 1 hrs to execute end to end flow so please suggest how to fix token expiry issue across the microservices.

**Comment by JonasKs** [comment]
> Some micro-services take more than 1 hrs to execute end to end flow so please suggest how to fix token expiry issue across the microservices.

I think we need more information about what you’re initial goal is here. Sounds to me that you should make one endpoint to kick off the flow, and another to check the status of the flow.

**Comment by jobec** [comment]
Do you have links to the packages you want to glue together?

Anyway, the expiry of the token is a setting on ADFS (not sure about azure). So Google the docs for ADFS and you'll find it.

On the other hand, calling a microservice that takes an hour sounds like an architectural issue. You'll start to bump into all sorts of timeouts. Not only from the token but also things like firewalls an the like.
Might be better to look into things like Celery and handle it as background tasks. The call to the microservice would then immediately return the task id. The caller can then request the task status every so often to check it's progress.

**Comment by jobec** [comment]
You want to use django-auth-adfs to integrate DjangoRestFramework with AzureAD?
But at the same time also use Django (without the rest framework) to login using a login page?

Maybe take some time to give a more detailed explanation using package/product names. Because the way you describe your problem now makes it difficult to understand what exactly you want to do.

Anyway, it should be possible to have multiple Django authentication backends (https://docs.djangoproject.com/en/2.2/ref/settings/#std:setting-AUTHENTICATION_BACKENDS). As does Django Rest Framework: https://www.django-rest-framework.org/api-guide/authentication/#setting-the-authentication-scheme

So it all depends on what exactly you want and where you send your users to to authenticate.

**Comment by jobec** [comment]
Closed because of inactivity. Feel free to reopen if you have more questions.
