### ISSUE TITLE
Store access_token to make querys to Microsoft Graph

### ISSUE THREAD

**Issue by Seykotron** [jobec/django-auth-adfs#91]
Is there any way to store the access_token used to loggin to make Microsoft Oauth calls like:

https://docs.microsoft.com/en-us/previous-versions/office/office-365-api/api/version-2.0/photo-rest-operations

Thank you!

**Comment by jobec** [comment]
In what situation would you like to use that token? Because, by default, django's user authentication just returns a user object. Nothing else.

https://github.com/jobec/django-auth-adfs/blob/84062cd8eda03dee704fafc4ed1c636d40ef1546/django_auth_adfs/backend.py#L266-L267

Making the token available would mean storing it somewhere. But where, depends on your use case.

**Comment by Seykotron** [comment]
I found what I were looking for.

I needed unpersonalized access to the Microsoft Graph, so thank you for your time! :)
